export const question = [
  {
    question: 'are there iron in plantains?',
    type_question: 'simple',
    response_category: 'boolean',
    response_type: 'boolean',
    relation: '',
    entity: '',
    Answer: 'Of Course, there are iron in plantains.',
  },
  {
    question: 'What ingredients are there in plantains and okorobong?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entity:
      'The ingredients are plantains, okorobong, meat, egusi or groundnuts, and onions',
  },
  {
    question: 'Which Gambian foods has more nutritional value?',
    type_question: 'comparison',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entity: '',
    answer:
      'White rice and sauces, Banachin, Yassa, Cassava and beans, yassa. ',
  },
  {
    question: 'are there proteins in Nkwan Nkwanlan?',
    type_question: 'simple',
    response_category: 'boolean',
    response_type: 'boolean',
    relation: '',
    entity: '',
    answer: 'Of course, there are proteins in Nkwan Nkwanlan',
  },
  {
    question: 'Which food is more delicious?',
    type_question: 'comparison',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entity: '',
    answer: 'White rice and sauces',
  },
  {
    question: 'Do Gambian foods difficult to cook?',
    type_question: 'simple',
    response_category: 'boolean',
    response_type: 'boolean',
    relation: '',
    entity: '',
    answer: 'Yes, some foods prepare in Gambia are more tedious than others.',
  },
  {
    question: 'Which Gambia foods has more nutritional value?',
    type_question: 'comparison',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entity: '',
    answer:
      'Here are some list of foods that are nutritive in Gambia. They include; White rice and sauces, Akara, Yassa and Okra Stew.',
  },
  {
    question: 'How is akara beans prepared or cooked?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entity: '',
    answer:
      'First the beans is smashed finely, then add an appropriate amount of salt and maggi for it good taste, then mold the beans in the shape of your choice and then fry it.',
  },
  {
    question: 'What makes Gambian food the one of the best in Africa?',
    type_question: 'constraint',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entity: '',
    answer:
      'Due to their unique techniques in cooking as well as their rich soils which produce rich crops, makes Gambian food one of the best in taste in Africa. ',
  },
  {
    question: 'What are the benefits of drinking water regularly?',
    type_question: 'constraint',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entity: '',
    answer:
      'Water helps to keep the body hydrated, improves blood circulation, prevent kidney stones, improve hair texture, and also helps in body metabolism.',
  },
  {
    question: 'What quantity of water should I drink daily?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entity: '',
    answer:
      'According to the U.S National Academies of Sciences, Engineering, and Medicine determined that an adequate daily fluid intake is; about 3.7 litters for men and 2.7 litters for Women.',
  },
  {
    question: 'are they foods in Gambia that causes constipation?',
    type_question: 'simple',
    response_category: 'boolean',
    response_type: 'boolean',
    relation: '',
    entity: '',
    answer:
      'Yes, some food or meals in Gambia cause constipation to some people.',
  },
  {
    question: 'Do calcium and protein found in Plantains and beans?',
    type_question: 'simple',
    response_category: 'boolean',
    response_type: 'boolean',
    relation: '',
    entity: '',
    answer: 'Yes, there are calcium and proteins found in plantains and beans.',
  },
  {
    question: 'are vegetables important to the human body?',
    type_question: 'simple',
    response_category: 'boolean',
    response_type: 'boolean',
    relation: '',
    entity: '',
    answer: 'Yes, they are important to the human body.',
  },
  {
    question: 'What are the importance of vegetables in the body?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entity: '',
    answer:
      'It reduce the risk of heart disease and prevents stroke, has positive effect upon blood sugar, prevent some types of caner, improves skin and amongst others.',
  },
  {
    question: 'When is the best time to eat?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'date',
    relation: '',
    entity: '',
    answer:
      '6:00 to 9:45a.m. is the best time for breakfast, 10a.m. for snack time, 1p.m. for lunch break and 6p.m. for Dinnertime',
  },
  {
    question: 'When is the appropriate time to drink water?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'date',
    relation: '',
    entity: '',
    answer:
      'First, when you wake up in the morning, 30 minutes before and after Meals. ',
  },
  {
    question: 'Who should drink more milk? children or adults?',
    type_question: 'comparison',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entity: '',
    answer: 'Children should drink more milk than adults',
  },
  {
    question: 'How much calcium is found in rice?',
    type_question: 'simple',
    response_category: 'boolean',
    response_type: 'boolean',
    relation: '',
    entity: '',
    answer: '158g of rice contains 15.80mg of calcium.',
  },
  {
    question: 'How much iron is found in plantains?',
    type_question: 'simple',
    response_category: 'boolean',
    response_type: 'boolean',
    relation: '',
    entity: '',
    answer: 'It has 0.6mg of iron',
  },
  {
    question: 'Which food contains less proteins?',
    type_question: 'comparison',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entity: '',
    answer: 'Vegetables and Grains contains less proteins.',
  },
  {
    question: 'Which food is most enjoyed by Gambians?',
    type_question: 'comparison',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entity: '',
    answer: 'White Rice and sauces',
  },
  {
    question: 'How is starch important to children and adults?',
    type_question: 'contraint',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entity: '',
    answer: 'It gives energy to children and adults',
  },
  {
    question: 'Which Gambia foods has more nutritional value?',
    type_question: 'comparison',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entity: '',
    answer: 'White Rice and sauces',
  },
  {
    question: 'is fish rich in protein?',
    type_question: 'simple',
    response_category: 'boolean',
    response_type: 'boolean',
    relation: '',
    entite: '',
    answer: 'Yes.',
  },
  {
    question: 'Which are the best top 5 foods in Gambia?',
    type_question: 'comparison',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entite: '',
    answer:
      'The top five foods eaten in Gambia are; Benachin, White Rice and sauces, Akara, Yassa and Okra Stew.',
  },
  {
    question: 'What are the vitamins found in Plantains?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entite: '',
    answer:
      'The vitamins include; iron, vitamin B6, Magnesium, Vitamin D, Vitamin C, Calcium, and Cobalamin.',
  },
  {
    question: 'How are vitamins important to the human body?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entite: '',
    answer:
      'They are minerals that helps the boyd develop and function as it should be. They help in the development of strong bones, repair body tissues, Protects the brain and the heart and amongst others.',
  },
  {
    question: 'which are the best fruits in Gambia?',
    type_question: 'simple',
    response_category: 'comparison',
    response_type: 'string',
    relation: '',
    entite: '',
    answer: 'They are mangoes, papaya, lemon, oranges and grapefruit.',
  },
  {
    question: 'why are fruits important to the human body?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entite: '',
    answer:
      'They contain rich vitamins such as Vitamin C and Vitamin A, they are rich in fibre, improve digestive system, maintain good health and so much more.',
  },
  {
    question: 'Why is it essential to eat fruits?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entite: '',
    answer:
      'They contain rich vitamins such as Vitamin C and Vitamin A, they are rich in fibre, improve digestive system, maintain good health and so much more.',
  },
  {
    question: 'Why people eat vegetables?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'string',
    relation: '',
    entite: '',
    answer:
      'It reduce the risk of heart disease and prevents stroke, has positive effect upon blood sugar, prevent some types of caner, improves skin and amongst others.',
  },
  {
    question: 'Which is the best food people love to eat in Gambia?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'name',
    relation: '',
    entite: '',
    answer: 'White rice and sauces',
  },
  {
    question: 'Which are the most common fruits in Gambia?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'name',
    relation: '',
    entite: '',
    answer:
      'The common fruits in Gambia are mangoes, grapefruit, papaya, lemon, and oranges.',
  },
  {
    question: 'When is cultivation of crops taking place in Gambia?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'date',
    relation: '',
    entite: '',
    answer: 'Most during the raining season starting from the month of March.',
  },
  {
    question: 'Whose meal or food is best in Gambia?',
    type_question: 'comparison',
    response_category: 'literal',
    response_type: 'name',
    relation: '',
    entite: '',
    answer: 'White rice and sauces',
  },
  {
    question: 'How much vitamins are there in maize or corn?',
    type_question: 'simple',
    response_category: 'literal',
    response_type: 'number',
    relation: '',
    entite: '',
    answer:
      'There are main four vitamins which are Vitamin C, Vitamin B, Magnesium and Potassium.',
  },
];
export const predire = [
  {
    jour: 0,
    resultat: 'plantain viande',
    Pourcentage: 100,
  },
  {
    jour: 1,
    resultat: 'couscous sauce gombo',
    Pourcentage: 40,
  },
  {
    jour: 2,
    resultat: 'spaghetti sardine',
    Pourcentage: 26.666666666666668,
  },
  {
    jour: 3,
    resultat: 'pistache baton',
    Pourcentage: 17.833333333333336,
  },
  {
    jour: 4,
    resultat: 'plantain viande',
    Pourcentage: 16.10166666666667,
  },
  {
    jour: 5,
    resultat: 'plantain viande',
    Pourcentage: 17.602833333333333,
  },
  {
    jour: 6,
    resultat: 'plantain viande',
    Pourcentage: 16.261198611111112,
  },
  {
    jour: 7,
    resultat: 'plantain viande',
    Pourcentage: 14.329650833333336,
  },
  {
    jour: 8,
    resultat: 'plantain viande',
    Pourcentage: 15.074069101851856,
  },
  {
    jour: 9,
    resultat: 'plantain viande',
    Pourcentage: 15.55345492337963,
  },
];
const search = { question, predire };
export default search;
